app:
  build: .
  command: python -u app.py
  ports:
    - "5000:5000"
  volumes:
    - .:/app
  links:
    - db
db:
  image: mongo:latest
  hostname: hostel_leave
  environment:
     - MONGO_INITDB_DATABASE=user_login
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=pass
  ports:
    - "27017:27017"
  volumes:
    - ./init.js:/docker-entrypoint-initdb.d/init-db.js:ro

